### PR TITLE
fix(text field): adds missing adapter method `notifyIconAction` on Icon 

### LINKED ISSUE #585: TextField/Icon missing adapter methods `notifyIconAction`,`registerInteractionHandler`, and `deregisterInteractionHandler`
Textfield/Icon is missing adapter methods `notifyIconAction`, `registerInteractionHandler`, and `deregisterInteractionHandler`. At the moment the latter two  are there to determine if the Icon has been activated from click or keydown events. 

I also note that it appears the material-components-web project has been removing de/registerInteractionHandlers in a lot of their adapters. With the preference to call register eventHandlers in `initialSyncWithDOM()`. This makes me wonder if these may also be removed in a future release.  Therefore, might only `notifyIconAction` be implemented?

### PR DESCRIPTION
**Pull request by mgr34**
Implements missing icon adapter method `notifyIconAction` on `<Icon/>`. Accomplished via adding optional `onSelect` to `<Icon/>` and corresponding `onLeadingIconSelect` and `onTrailingIconSelect` on `<TextField/>`. Still having trouble with screenshot tests. Should close #585. 

Note: this is the first I've worked with typescript. 

---

I signed it

### CODE REVIEW

File: packages/text-field/icon/index.tsx [hunk 1]
```diff
@@ -94,15 +108,27 @@ export default class Icon extends React.Component<
       removeAttr: (attr: keyof IconState) => (
         this.setState((prevState) => ({...prevState, [attr]: null}))
       ),
+      notifyIconAction: () => ( this.props.hasOwnProperty('onSelect')
+        ? this.props.onSelect!()
```
Comment (moog16) [inline packages/text-field/icon/index.tsx]: First time I'm doing a review on my phone... Do you have a default prop set for onSelect? We can get rid of the hasOwnProperty if you set one to an empty function

File: packages/text-field/icon/index.tsx [hunk 2]
```diff
@@ -77,6 +81,16 @@ export default class Icon extends React.Component<
     }
   }
 
+  get tabindex() {
+    // if tabIndex is not set onSelect will never fire.
+    // note that foundation.js alters tabindex not tabIndex
+    if (this.props.children.props.hasOwnProperty('tabIndex')) {
```
Comment (moog16) [inline packages/text-field/icon/index.tsx]: Instead of hasOwnProperty let's check if it is a number

File: packages/text-field/icon/index.tsx [hunk 3]
```diff
@@ -77,6 +81,16 @@ export default class Icon extends React.Component<
...
+      return this.props.children.props.tabIndex;
+    }
+
+    return this.props.hasOwnProperty('onSelect') ? 0 : -1;
```
Comment (moog16) [inline packages/text-field/icon/index.tsx]: We don't need to use hasOwnProperty, but instead just do this.props.onSelect

File: test/screenshot/text-field/icon/index.tsx [hunk 4]
```diff
@@ -15,6 +15,10 @@ const TextFieldIconScreenshotTest = () => {
       <Icon>
         <MaterialIcon tabIndex={0} role='button' icon='favorite' />
       </Icon>
+
```
Comment (moog16) [inline test/screenshot/text-field/icon/index.tsx]: Looks like you added a screenshot test! I'll update once the pr looks good. Thanks!

File: test/screenshot/text-field/TextFieldPermutations.tsx [hunk 5]
```diff
@@ -13,7 +13,11 @@ import {
 import TestField from './TestTextField';
 
 const textFields = (variantProps: {variant?: string}) => {
-  return iconsMap.map((icon: {leadingIcon?: React.ReactNode, trailingIcon?: React.ReactNode}) => {
+  return iconsMap.map((icon: {
+    leadingIcon?: React.ReactNode,
```
Comment (moog16) [inline test/screenshot/text-field/TextFieldPermutations.tsx]: something i notice about these tests is that the icon tap target is only 24px x 24px. HIG (human interface guide - I think) says 48x48 is the minimum. I'm not sure what MDC Web does or if this is an issue with MDC Web. I'll follow up with one of our engineers.

File: packages/text-field/icon/index.tsx (hunk 1 above)
Comment (mgr34) [reply packages/text-field/icon/index.tsx]: I think this might be an appropriate use for `hasOwnProperty`. Shortly I will be pushing a change where I eliminate it from the get tabidex(). 

I consciously chose against the approach of making it a defaultProp. Coincidentally, that is how I first went about it [0]. However, I ran into a problem where onSelect will only fire if tabindex != -1 due to pointer-events being set to none [1]. Since tabindex was not a required property for the passed icon I thought it more straightforward to add it based on if onSelect is present. If its has a default prop it will always be present and tabindex will always be initialized with 0 unless specified. This was the major factor in my decision to drop it as a default property.

I also seem to recall an issue in renderIcon from text-field where It was always passing an onSelect. Alas, I cannot quite recall the issue there and it was never committed. Maybe I was also setting a default prop for onLeadingIconSelect/onTrailingIconSelect?

Take your time on responding. A code review on a phone sounds painful.
 

[0] - https://github.com/material-components/material-components-web-react/pull/600/commits/df8627c239b047c58a3353743b2838369c689516#diff-78f850e429f25a98280e040459f8b54f

[1] https://github.com/material-components/material-components-web/blob/3cc4c6aa48ae8c1a307df542911e28a7808de41f/packages/mdc-textfield/icon/mdc-text-field-icon.scss#L33-L37

File: test/screenshot/text-field/TextFieldPermutations.tsx [hunk 6]
```diff
@@ -13,7 +13,11 @@ import {
 import TestField from './TestTextField';
 
 const textFields = (variantProps: {variant?: string}) => {
-  return iconsMap.map((icon: {leadingIcon?: React.ReactNode, trailingIcon?: React.ReactNode}) => {
+  return iconsMap.map((icon: {
```
Comment (moog16) [inline test/screenshot/text-field/TextFieldPermutations.tsx]: also getting an error when click on the leading-trailing-icon permutation. Try clicking on one of the icons here:
tndrewahb7u

They also should not have `tabIndex` at all. It should be undefined.

File: packages/text-field/icon/index.tsx [hunk 7]
```diff
@@ -27,6 +27,7 @@ import {MDCTextFieldIconFoundation} from '@material/textfield/dist/mdc.textfield
 export interface IconProps extends React.HTMLProps<HTMLOrSVGElement> {
   disabled: boolean;
   children: React.ReactElement<React.HTMLProps<HTMLOrSVGElement>>;
+  onSelect?: () => void;
```
[the remark this answers is not in the document]
Comment (mgr34) [reply packages/text-field/icon/index.tsx]: can do.

File: packages/text-field/index.tsx [hunk 8]
```diff
@@ -45,6 +45,8 @@ export interface Props<T> {
   lineRippleClassName: string;
   notchedOutlineClassName: string;
   outlined: boolean;
+  onLeadingIconSelect?: () => void;
```
[the remark this answers is not in the document]
Comment (mgr34) [reply packages/text-field/index.tsx]: See my previous response about why I did not include a default prop for onSelect. This would hoist the problem. Now renderIcon will always render with an onSelect and would be problematic for setting the tabindex.

File: packages/text-field/icon/index.tsx (hunk 1 above)
Comment (moog16) [reply packages/text-field/icon/index.tsx]: That makes sense about the defaultProp...but we don't use hasOwnProperty anywhere else in the library, which makes me suspicious. Either we should be doing that everywhere, or we shouldn't do it here - it just breaks the pattern. If we decide to do it, we should instead open another bug to do it system wide.

File: packages/text-field/index.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (moog16) [reply packages/text-field/index.tsx]: sounds good!

File: packages/text-field/icon/index.tsx (hunk 1 above)
Comment (mgr34) [reply packages/text-field/icon/index.tsx]: I hear you on  that mindset....I guess I could do something like the following. 

```typescript
{ notifyIconAction: (() =>  this.props.onSelect ? this.props.onSelect() : null) }
```

for some reason I seem to rely heavily on hasOwnProperty() in other projects. Old habits and all... Nevertheless, making this exact change doesn't seem to cause any breaking changes. Will this work for you?

Comment (moog16) [reply packages/text-field/icon/index.tsx]: looks good to me!

File: test/screenshot/text-field/TextFieldPermutations.tsx (hunk 6 above)
Comment (moog16) [reply test/screenshot/text-field/TextFieldPermutations.tsx]: cool - i think one of your other commits must have fixed it

File: packages/text-field/icon/README.md [hunk 9]
```diff
@@ -22,6 +22,9 @@ Prop Name | Type | Description
 --- | --- | ---
 disabled | Boolean | Toggles the disabled state of the icon.
 children | Element | Required. Expects a single child icon element.
+onSelect | Function() => void | Optional callback for user interaction with icon
+> Notes: `onSelect`  fired only for clicked event or when keydown event is enter key.
```
Comment (moog16) [inline packages/text-field/icon/README.md]: wording: `fired on click event and "enter key" keydown event.

File: test/unit/text-field/index.test.tsx [hunk 10]
```diff
@@ -478,6 +517,34 @@ test('does not render trailingIcon or trailingIcon if no prop is passed', () =>
   assert.equal(wrapper.find('.test-class-name-icon').length, 0);
 });
 
+test('onTrailingIconSelect is passed to trailingIcion if passed as prop', () => {
```
Comment (moog16) [inline test/unit/text-field/index.test.tsx]: trailingIcon spelling mistake

File: test/unit/text-field/index.test.tsx [hunk 11]
```diff
@@ -478,6 +517,34 @@ test('does not render trailingIcon or trailingIcon if no prop is passed', () =>
...
+      trailingIcon={<i className='test-class-name-icon' />}
+    ><Input /></TextField>
+  );
+
+  const trailingIcon = wrapper.find('.test-class-name-icon').parent().props();
+  assert.isFunction(trailingIcon.onSelect);
+  assert.strictEqual(trailingIcon.onSelect, onSelect);
+});
+
+test('onTrailingIconSelect is not passed to trailingIcion if not passed as prop', () => {
```
Comment (moog16) [inline test/unit/text-field/index.test.tsx]: Icon spelling

**Comment by moog16** [comment]
@mgr34 please update text-field/icon golden.json to `0bbc8c762d27071e55983e5742548d166864b6fcebc0b9f1e413523fb93b7075`

File: test/unit/text-field/index.test.tsx (hunk 10 above)
Comment (mgr34) [reply test/unit/text-field/index.test.tsx]: fixed!

**Comment by moog16** [comment]
tests are passing and pr is signed in https://github.com/material-components/material-components-web-react/pull/600#issue-243022107. Merging!
