### PR TITLE
fix(ripple): Adds HTMLElement shim to fix regression for SSR projects

### LINKED ISSUE #581: ripple: HTMLElement is not defined on SSR
Hello,

With the changeover to TS in `v0.8.0`, the following [line](https://github.com/material-components/material-components-web-react/blob/v0.7.1/packages/ripple/index.js#L65) went from being scoped within a function to [not](https://github.com/material-components/material-components-web-react/blob/v0.8.0/packages/ripple/index.tsx#L29):
```js
const MATCHES = util.getMatchesProperty(HTMLElement.prototype);
```

In SSR React apps, this will result in an `HTMLElement is not defined` error, because it's not evaluated in a browser where `HTMLElement` would exist.

The following line, when added just before the line above, resolves the issue locally:

```ts
const HTMLElement = typeof HTMLElement === 'undefined' ? function () {} : HTMLElement;
```

However, I'm not sure this is an appropriate solution outside of my use case. If this addition would suffice, I can submit a PR for it. Let me know! Thanks! 😄

### PR DESCRIPTION
**Pull request by 4cm4k1**
This PR fixes #581.

I did not write any tests, as writing tests for SSR use cases is under consideration at #588.

The compiled result of the changed code is as follows, which should fix the regression seen in SSR projects:
```js
var HTMLElementShim = typeof HTMLElement === 'undefined' ? { } : HTMLElement;
var MATCHES = mdc_ripple_1.util.getMatchesProperty(HTMLElementShim.prototype);
```

I’m relatively new to writing TypeScript, so please let me know if `any` as a type should be changed.

Warm regards,
Anthony

### CODE REVIEW

File: packages/ripple/index.tsx [hunk 1]
```diff
@@ -26,7 +26,8 @@ import {Subtract} from 'utility-types'; // eslint-disable-line no-unused-vars
 // @ts-ignore no mdc .d.ts file
 import {MDCRippleFoundation, MDCRippleAdapter, util} from '@material/ripple/dist/mdc.ripple';
 
-const MATCHES = util.getMatchesProperty(HTMLElement.prototype);
+const HTMLElementShim: any = typeof HTMLElement === 'undefined' ? () => {} : HTMLElement;
```
Comment (moog16) [inline packages/ripple/index.tsx]: Shouldn't the default be an object instead of a function?
```
const HTMLElementShim: any = typeof HTMLElement === 'undefined' ? {} : HTMLElement;
```

**Comment by moog16** [comment]
This looks like it fixed it, but I left one comment. I tested by using the repo linked in this issue https://github.com/material-components/material-components-web-react/issues/492. I actually found another similar issue using Drawer while testing. 

```
ReferenceError: Element is not defined
    at Object.105 (/usr/local/google/home/mattgoo/Downloads/material-next-template-master/node_modules/@material/drawer/dist/mdc.drawer.js:809:15)
    at __webpack_require__ (/usr/local/google/home/mattgoo/Downloads/material-next-template-master/node_modules/@material/drawer/dist/mdc.drawer.js:35:30)
```

I will open a separate issue.

File: packages/ripple/index.tsx (hunk 1 above)
Comment (4cm4k1) [reply packages/ripple/index.tsx]: Sure, can you explain why for me? I don’t necessarily understand what the difference is. I’ll make the change real quick. 👍

Comment (4cm4k1) [reply packages/ripple/index.tsx]: Done.

Comment (moog16) [reply packages/ripple/index.tsx]: On the next line you reference HTMLElementShim.prototype. That means that the HTMLElementShim should be an object - not a function.

Comment (4cm4k1) [reply packages/ripple/index.tsx]: Thank you!

**Comment by moog16** [comment]
@4cm4k1 could you please sign the pr

**Comment by moog16** [comment]
tests passing: https://github.com/material-components/material-components-web-react/pull/595

**Comment by 4cm4k1** [comment]
I signed it.

**Comment by moog16** [comment]
Thanks! merging :)
