### PR TITLE
fix: ClientRect/DOMRect is not IE11 compatible

### LINKED ISSUE #853: ClientRect is not defined
I've noticed that v.0.12 uses `new ClientRect()` in some places...

Well, I've been attempting to implement `mdc-slider` in React, and tried returning a `new ClientRect()` and got a `ClientRect is not defined` error.

Googling took me to: https://github.com/Microsoft/TypeScript/issues/18615

It seems that while TypeScript's typings still have `ClientRect`, Chrome has replaced it with `DOMRect` .

Further, `DOMRect` itself is experimental according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/DOMRect

I'm not sure if these are getting properly polyfilled by Webpack and Babel either.

Was there a specific reason to switch from the explicit `{ top: 0, right: 0, bottom: 0, left: 0, width: 0, height: 0 }` to `new ClientRect()`?

### PR DESCRIPTION
**Pull request by cpboyd**
Fixes #853.

@moog16 I copied the usage from `ripple` and `tab-bar` so that it'd be easier to do a find & replace in the future.

Let me know if there's anything else I need to do.

### CODE REVIEW

File: packages/tab-scroller/index.tsx [hunk 1]
```diff
@@ -151,14 +151,40 @@ export default class TabScroller extends React.Component<
...
-          this.areaElement.current.getBoundingClientRect() :
-          new ClientRect(),
-      computeScrollContentClientRect: () =>
-        this.contentElement.current ?
-          this.contentElement.current.getBoundingClientRect() :
-          new ClientRect(),
+      computeScrollAreaClientRect: () => {
+        if (!this.areaElement.current) {
+          // new DOMRect is not IE11 compatible
+          const defaultDOMRect = {
```
Comment (moog16) [inline packages/tab-scroller/index.tsx]: Could you make this a variable that both `computeScrollAreaClientRect` and `computeScrollContentClientRect` reference, instead of defining it twice?

Comment (cpboyd) [reply packages/tab-scroller/index.tsx]: I created a function `getBoundingClientRectOf` within `tab-scroller`.

I considered a shared variable (either within the class or the `adapter`) but if code happened to modify the returned object, then it would result in these functions no longer returning the expected default object.

File: packages/chips/Chip.tsx [hunk 2]
```diff
@@ -134,12 +134,38 @@ export class Chip extends React.Component<ChipProps, ChipState> {
...
+            y: 0,
+          };
+          return defaultDOMRect;
+        }
         return this.chipElement.getBoundingClientRect();
       },
       getCheckmarkBoundingClientRect: () => {
         const {chipCheckmark} = this.props;
-        if (!chipCheckmark) return new ClientRect();
+        if (!chipCheckmark) {
```
Comment (cpboyd) [inline packages/chips/Chip.tsx]: @moog16 Should this `if` also check `chipCheckmark.props.getBoundingClientRect`?

Comment (moog16) [reply packages/chips/Chip.tsx]: Yes, that doesn't hurt to have the check there.

Comment (moog16) [reply packages/chips/Chip.tsx]: I won't merge it if you want to update this...you may also want to check unit tests.

File: packages/tab-scroller/index.tsx [hunk 3]
```diff
@@ -151,19 +151,35 @@ export default class TabScroller extends React.Component<
...
+      },
+      computeScrollContentClientRect: () => {
+        return this.getBoundingClientRectOf(this.contentElement.current);
+      },
       computeHorizontalScrollbarHeight: () =>
         computeHorizontalScrollbarHeight(document),
     };
   }
 
+  getBoundingClientRectOf = (element: HTMLElement) => {
```
Comment (moog16) [inline packages/tab-scroller/index.tsx]: This looks good.

File: packages/chips/Chip.tsx (hunk 2 above)
Comment (cpboyd) [reply packages/chips/Chip.tsx]: Added new commit.

Couldn't run tests due to fsevents failing to build on Node v12 on Mac.

I'll try to see about switching to nvm tomorrow and running the tests.

**Comment by cpboyd** [comment]
@moog16 The new commit fixed the unit tests.

Let me know if you want me to rebase these changes down to a single commit.
