### PR TITLE
fix(tab-bar): Arrow keys should focus adjacent tab

### LINKED ISSUE #279: Focus is not visible on tabs
When you click on a tab, the ripple activates but the ripple's focus background color is not present.

### PR DESCRIPTION
**Pull request by bonniezhou**
Fixes #279 and #276

### CODE REVIEW

File: packages/tab-bar/index.js [hunk 1]
```diff
@@ -63,11 +63,12 @@ export default class TabBar extends Component {
       getPreviousActiveTabIndex: () => this.state.previousActiveIndex,
       getFocusedTabIndex: () => {
         const activeElement = document.activeElement;
-        this.tabList_.forEach((tabList, index) => {
-          if (tabList.tabElement_.current === activeElement) {
-            return index;
+        for (let i = 0; i < this.tabList_.length; i++) {
```
Comment (moog16) [inline packages/tab-bar/index.js]: I don't think you need this change.

File: test/unit/tab/index.test.js [hunk 2]
```diff
@@ -305,3 +305,25 @@ test('#componentWillUnmount destroys foundation', () => {
   wrapper.unmount();
   td.verify(foundation.destroy(), {times: 1});
 });
+
+test('on focus event calls handleFocus on TabRipple', () => {
+  const wrapper = shallow(<Tab />);
```
Comment (moog16) [inline test/unit/tab/index.test.js]: It looks like you're trying to get the ref here...you can just use `mount` instead of shallow. Then these 3 lines can just be:

```
const wrapper = mount(<Tab />);
const ripple = wrapper.instance(). tabRipple_.current;
```

File: test/unit/tab/index.test.js [hunk 3]
```diff
@@ -305,3 +305,25 @@ test('#componentWillUnmount destroys foundation', () => {
...
+  wrapper.instance().tabRipple_ = {current: ripple};
+  ripple.handleFocus = td.func();
+
+  const evt = {test: 'test'};
+  wrapper.simulate('focus', evt);
+  td.verify(ripple.handleFocus(evt), {times: 1});
+});
+
+test('on blur event calls handleBlur on TabRipple', () => {
+  const wrapper = shallow(<Tab />);
```
Comment (moog16) [inline test/unit/tab/index.test.js]: same here

File: packages/tab-bar/index.js (hunk 1 above)
Comment (bonniezhou) [reply packages/tab-bar/index.js]: This is what's causing #276, the `forEach` is returning undefined

Comment (moog16) [reply packages/tab-bar/index.js]: ahh gotcha - lets just leave a comment so no one changes it back to a forEach or something

**Comment by bonniezhou** [comment]
Good call 👍
