### PR TITLE
fix(text-field): label isn't float when set value with setState

### LINKED ISSUE #895: Floating label on text-field does not move when value prop changes.
image

### PR DESCRIPTION
**Pull request by TroyTae**
fixes #895

**breaking changes**
`handleValueChange` is removed from Input's props.

### CODE REVIEW

**Comment by TroyTae** [comment]
Ah I see, then I'll close this PR..!

File: packages/text-field/Input.tsx [hunk 1]
```diff
@@ -163,16 +166,24 @@ export default class Input<
     }
 
     if (value !== prevProps.value) {
```
Comment (moog16) [inline packages/text-field/Input.tsx]: Let's reopen it, cause I think this is where the change should happen. I think this `if` block should look like this: 
```
if (value !== prevProps.value) {
      const inputValue = this.valueToString(value);
      const notTriggeredChange = !this.state.wasUserTriggeredChange;
      // only call #foundation.setValue on programatic changes;
      // not changes by the user.
      if (notTriggeredChange) {
        foundation && foundation.setValue(inputValue);
      }

      this.setState({wasUserTriggeredChange: false});
    }
```

File: packages/text-field/index.tsx [hunk 2]
```diff
@@ -287,6 +287,7 @@ class TextField<
     const {props} = React.Children.only(this.props.children);
 
     return Object.assign({}, props, {
+      adapter: this.adapter,
```
Comment (moog16) [inline packages/text-field/index.tsx]: remove the adapter from here

File: packages/text-field/Input.tsx (hunk 1 above)
Comment (TroyTae) [reply packages/text-field/Input.tsx]: I reflected it!
Is handleValueChange a breaking change?
I saw and removed a test code that checks call count of handleValueChange.

Comment (moog16) [reply packages/text-field/Input.tsx]: Can you remove handleValueChange from everywhere? https://github.com/material-components/material-components-web-react/pull/934/files#diff-0eddc9611a42aba741f3ee96c819757eR31

This is a "breaking change" however no one should have been using this.

**Comment by moog16** [comment]
please remove handlevalueChange from all tests and source code:  https://github.com/material-components/material-components-web-react/blob/c5ad27e913a8002892d58949d588e5b8fc8c1a10/test/unit/text-field/Input.test.tsx#L183

**Comment by TroyTae** [comment]
@moog16 
I reflected it!
I guess we need to descript about this in CHANGELOG.md :)

**Comment by moog16** [comment]
Changelog is generated - so not worries about CHANGELOG. Changes look good!
